---

- name: Déploiement du serveur Apache
  hosts: webservers
  become: true
  vars_files:
    - "../roles/apache/vars/main.yml"
  roles:
    - ../roles/apache

- name: Déploiement de la base MySQL
  hosts: dbservers
  become: true
  vars_files:
    - "../roles/mysql/vars/main.yml"
  roles:
    - ../roles/mysql

- name: Déploiement de l'application
  hosts: appservers
  become: true
  roles:
    - ../roles/webapp
