---

- name: Déploiement Apache
  hosts: webservers #, appservers
  become: true
  vars_files:
    - "../roles/apache/vars/main.yml"
  roles:
    - ../roles/apache

- name: Déploiement mysql
  hosts: dbservers
  become: true
  vars_files:
    - "../roles/mysql/vars/main.yml"
  roles:
    - ../roles/mysql

- name: Déployer l'application web sur les appservers
  hosts: appservers
  become: true
  roles:
    - ../roles/webapp
