---
- name: Installer Apache
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Configurer Apache
  template:
    src: ../templates/apache.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: restart apache

- name: Démarrer Apache
  service:
    name: apache2
    state: started
    enabled: yes
