---
- name: Purge complète d'Apache
  apt:
    name: apache2
    state: absent
    purge: yes
    autoremove: yes
  tags: purge

- name: Installer Apache
  apt:
    name: apache2
    state: latest

- name: Configurer Apache
  template:
    src: ../templates/apache.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: restart apache

- name: Désactiver les autres MPM
  command: "a2dismod mpm_{{ item }}"
  loop: "{{ mpm_to_disable }}"
  ignore_errors: yes
  notify: restart apache

- name: Activer mpm_prefork
  command: "a2enmod mpm_prefork"
  notify: restart apache
