---
- name: Installer Apache
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Configurer Apache
  template:
    src: ../templates/apache.conf.j2
    dest: /etc/apache2/apache2.conf
  notify: restart apache

- name: Démarrer Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Copier le fichier index.php
  copy:
    src: ~/devops-tps/tp3/roles/webapp/files/index.php
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Installer PHP
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes
